default_context:
    project_name: "application_file_scanner"
    pypi_package_name: "application_file_scanner"
    github_organization: "jackdewinter"
    github_project_name: "application_file_scanner"
    one_line_setup_description : "A small package to deal with the headaches of scanning for files for an application to execute on."
    setup_intended_audience : "\"Intended Audience :: Developers\","
    setup_additional_classifier : "\"Topic :: Software Development :: Libraries :: Application Frameworks\","
    setup_keywords : "\"properties\""
